# Generated by Django 3.1.5 on 2021-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20210131_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('rcv', 'Получено'), ('prc', 'В обработке'), ('rpl', 'Ответ отправлен')], default='rcv', max_length=3),
        ),
    ]
