# Generated by Django 3.1.5 on 2021-01-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210129_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('teachers', models.ManyToManyField(related_name='courses', to='users.Teacher')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(verbose_name='Дата окончания обучения')),
                ('certificate_issue_date', models.DateField(verbose_name='Дата выдачи сертификата')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_group', to='courses.course')),
                ('students', models.ManyToManyField(related_name='course_groups', to='users.Student')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('finish_time', models.DateTimeField(verbose_name='Время окончания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='courses.coursegroup')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
