# Generated by Django 3.1.5 on 2021-01-31 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения урока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='finish_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
    ]
